[package]
name = "t-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
no-std-compat = "0.4.1"
serde = "1.0.206"
serde_derive = "1.0.206"
wasm-bindgen = {version = "0.2.92", optional = true }

[features]
default = ["local"] 
local = ["no-std-compat/std"]
