[package]
name = "program"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.0", default-features = false, features = ['std'] }
userscrate = { path = "../../userscrate" }
t-rust = { path = "../../../../../t-rust/", features = ["risc0"] }