[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
args = { path = "../../../../args/" }
hex = "0.4.3"
methods = { path = "../methods" }
risc0-zkvm = { version = "1.2.0" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
